const fs = require('fs');
const path = require('path');

/* Ready-made logo designs sold at a fixed price.
   Mirrors build-projects.js: one folder per logo under /logos with a logo.json
   plus its images, flattened here into logos-data.js for the client and SSR. */

const logosDir  = path.join(__dirname, 'logos');
const outputFile = path.join(__dirname, 'logos-data.js');

if (!fs.existsSync(logosDir)) {
  console.error(`Missing folder: ${logosDir}`);
  process.exit(1);
}

const folders = fs.readdirSync(logosDir).filter(f =>
  fs.statSync(path.join(logosDir, f)).isDirectory() &&
  fs.existsSync(path.join(logosDir, f, 'logo.json'))
);

const logos = {};

folders.forEach(folder => {
  const file = path.join(logosDir, folder, 'logo.json');
  let json;
  try {
    json = JSON.parse(fs.readFileSync(file, 'utf8'));
  } catch (err) {
    console.error(`  ! Invalid JSON in ${folder}/logo.json — skipped\n    ${err.message}`);
    return;
  }

  const slug    = json.slug || folder;
  const imgBase = `/logos/${folder}/`;
  const img     = f => (f ? imgBase + f : '');
  const loc     = (obj, l) => (obj && (obj[l] || obj.en || obj.de)) || {};

  /* Every image on the detail page, in order. The first doubles as the card
     thumbnail unless `thumbnail` names a different one. */
  const images = (json.images || []).map((im, i) => {
    const src = typeof im === 'string' ? im : im.src;
    const alt = typeof im === 'string' ? {} : (im.alt || {});
    return { src: img(src), i, alt: { en: loc(alt, 'en') || alt || '', de: loc(alt, 'de') || alt || '' } };
  });

  if (!images.length) console.warn(`  ! ${folder} lists no images`);
  if (!json.price)    console.warn(`  ! ${folder} has no price — the card will show nothing`);

  /* Sort key: lower `order` first, then alphabetical. */
  let ord = Number(json.order);
  if (!Number.isFinite(ord)) ord = 999;

  logos[slug] = {
    slug,
    ord,
    price: json.price || '',
    /* 'available' | 'sold' — a sold logo stays listed but cannot be enquired about */
    status: json.status === 'sold' ? 'sold' : 'available',
    thumb: img(json.thumbnail || (json.images && (typeof json.images[0] === 'string' ? json.images[0] : json.images[0]?.src)) || 'hero.webp'),
    c: json.color || '#1a1a1a',
    en: {
      name:  loc(json, 'en').name || json.name || slug,
      tag:   loc(json, 'en').tagline || '',
      desc:  loc(json, 'en').description || '',
      tags:  loc(json, 'en').tags || [],
      incl:  loc(json, 'en').includes || []
    },
    de: {
      name:  loc(json, 'de').name || json.name || slug,
      tag:   loc(json, 'de').tagline || '',
      desc:  loc(json, 'de').description || '',
      tags:  loc(json, 'de').tags || [],
      incl:  loc(json, 'de').includes || []
    },
    images
  };
});

const sortedKeys = Object.keys(logos).sort((a, b) =>
  logos[a].ord !== logos[b].ord ? logos[a].ord - logos[b].ord : a.localeCompare(b));

const sorted = {};
sortedKeys.forEach(k => { sorted[k] = logos[k]; });

const output = `/* Auto-generated by build-logos.js — do not edit manually */
const LG = ${JSON.stringify(sorted, null, 2)};

/* ===== Universal export: works in browser AND Node (SSR). Browser ignores this. ===== */
if (typeof module !== 'undefined' && module.exports) { module.exports = { LG: LG }; }
`;

fs.writeFileSync(outputFile, output, 'utf8');

console.log(`Built ${sortedKeys.length} logos → logos-data.js`);
sortedKeys.forEach(k => console.log(`    ${String(logos[k].ord).padStart(3)}  ${k}  ${logos[k].price || '(no price)'}  [${logos[k].status}]  ${logos[k].images.length} images`));
