const fs = require('fs');
const path = require('path');

const fontsDir = path.join(__dirname, 'ownfonts');
const outputDataFile = path.join(__dirname, 'fonts-data.js');
const outputCssFile = path.join(__dirname, 'fonts-generated.css');

// Read all font folders that contain a font.json
const folders = fs.readdirSync(fontsDir).filter(f =>
  fs.statSync(path.join(fontsDir, f)).isDirectory() &&
  fs.existsSync(path.join(fontsDir, f, 'font.json'))
);

const fonts = [];
const fontFaces = [];

folders.forEach(folder => {
  const json = JSON.parse(fs.readFileSync(path.join(fontsDir, folder, 'font.json'), 'utf8'));
  const slug = json.slug || folder.toLowerCase().replace(/\s+/g, '-');
  const baseUrl = `/ownfonts/${folder}/`;

  // Build @font-face declarations from the font files
  if (json.files) {
    if (json.files.regular) {
      const ext = path.extname(json.files.regular).slice(1);
      const format = ext === 'otf' ? 'opentype' : ext === 'ttf' ? 'truetype' : ext === 'woff2' ? 'woff2' : ext === 'woff' ? 'woff' : 'opentype';
      fontFaces.push(`@font-face{font-family:'${json.family}';src:url('${baseUrl}${json.files.regular}') format('${format}');font-weight:400;font-style:normal;font-display:swap}`);
    }
    if (json.files.italic) {
      const ext = path.extname(json.files.italic).slice(1);
      const format = ext === 'otf' ? 'opentype' : ext === 'ttf' ? 'truetype' : ext === 'woff2' ? 'woff2' : ext === 'woff' ? 'woff' : 'opentype';
      fontFaces.push(`@font-face{font-family:'${json.family}';src:url('${baseUrl}${json.files.italic}') format('${format}');font-weight:400;font-style:italic;font-display:swap}`);
    }
    if (json.files.bold) {
      const ext = path.extname(json.files.bold).slice(1);
      const format = ext === 'otf' ? 'opentype' : ext === 'ttf' ? 'truetype' : ext === 'woff2' ? 'woff2' : ext === 'woff' ? 'woff' : 'opentype';
      fontFaces.push(`@font-face{font-family:'${json.family}';src:url('${baseUrl}${json.files.bold}') format('${format}');font-weight:700;font-style:normal;font-display:swap}`);
    }
  }

  // Build image paths
  const images = (json.images || []).map(img => baseUrl + img);

  // Build the font data object
  const fontData = {
    name: json.name,
    slug: slug,
    family: json.family,
    hasItalic: json.hasItalic || false,
    preview: json.preview || 'The quick brown fox jumps over the lazy dog',
    desc: {
      en: json.en.description,
      de: json.de.description
    },
    meta: {
      designer: json.meta.designer,
      version: json.meta.version,
      update: json.meta.update,
      formats: json.meta.formats
    },
    // Font style label shown on the card (e.g. "Regular + Italic", "Mono", "Display")
    cardLabel: json.cardLabel || (json.hasItalic ? 'Regular + Italic' : 'Regular'),
    // Download
    downloadable: json.downloadable || false,
    downloadFile: json.downloadable && json.downloadFile ? baseUrl + json.downloadFile : null,
    // Individual font files (for the tester's @font-face and fallback download)
    files: {
      regular: json.files && json.files.regular ? baseUrl + json.files.regular : null,
      ...(json.files && json.files.italic ? { italic: baseUrl + json.files.italic } : {}),
      ...(json.files && json.files.bold ? { bold: baseUrl + json.files.bold } : {})
    },
    // Bento grid images
    images: images,
    // Display order (lower = first)
    order: json.order ?? 999
  };

  fonts.push(fontData);
});

// Sort by order ascending
fonts.sort((a, b) => a.order - b.order);

// Write fonts-data.js
const dataOutput = `/* Auto-generated by build-fonts.js — do not edit manually */\nconst FONTS = ${JSON.stringify(fonts, null, 2)};\n`;
fs.writeFileSync(outputDataFile, dataOutput, 'utf8');

// Write fonts-generated.css
const cssOutput = `/* Auto-generated by build-fonts.js — do not edit manually */\n${fontFaces.join('\n')}\n`;
fs.writeFileSync(outputCssFile, cssOutput, 'utf8');

console.log(`Built ${fonts.length} fonts → fonts-data.js`);
console.log(`Generated ${fontFaces.length} @font-face rules → fonts-generated.css`);
fonts.forEach(f => console.log(`  ${f.name} (${f.slug}) — order ${f.order}${f.downloadable ? ' [downloadable]' : ''}`));
