/* Auto-generated by build-fonts.js — do not edit manually */
const FONTS = [
  {
    "name": "Perception",
    "slug": "perception",
    "family": "Perception",
    "hasItalic": false,
    "preview": "The quick brown fox jumps over the lazy dog",
    "desc": {
      "en": "Eine Monospace-Schrift, inspiriert von der LCD-Ästhetik. Klare Struktur trifft auf subtile Abrundungen.",
      "de": "A monospace font inspired by LCD aesthetics. Clean structure meets subtle rounded details."
    },
    "meta": {
      "designer": "Achim Benzel",
      "version": "1.0",
      "update": "2025",
      "formats": "OTF"
    },
    "cardLabel": "Mono",
    "downloadable": false,
    "downloadFile": null,
    "files": {
      "regular": "/ownfonts/Perception/Atest-mono.otf"
    },
    "images": [
      "/ownfonts/Perception/specimen.webp",
      "/ownfonts/Perception/glyphs.webp",
      "/ownfonts/Perception/weights.webp",
      "/ownfonts/Perception/in-use.webp",
      "/ownfonts/Perception/detail.webp"
    ],
    "order": 1
  },
  {
    "name": "CyberCell",
    "slug": "cybercell",
    "family": "CyberCell",
    "hasItalic": true,
    "preview": "The quick brown fox jumps over the lazy dog",
    "desc": {
      "en": "Eine kantige Y2K-Schrift mit technischer Anmutung. Verfügbar in Regular und Oblique. Für dynamische, digitale Anwendungen.",
      "de": "An angular Y2K typeface with a technical feel. Available in regular and oblique. For dynamic, digital use."
    },
    "meta": {
      "designer": "Achim Benzel",
      "version": "1.2",
      "update": "2024",
      "formats": "OTF"
    },
    "cardLabel": "Regular + Italic",
    "downloadable": false,
    "downloadFile": null,
    "files": {
      "regular": "/ownfonts/CyberCell/CyberCell.otf",
      "italic": "/ownfonts/CyberCell/CyberCell-Italic.otf"
    },
    "images": [
      "/ownfonts/CyberCell/specimen.webp",
      "/ownfonts/CyberCell/glyphs.webp",
      "/ownfonts/CyberCell/weights.webp",
      "/ownfonts/CyberCell/in-use.webp",
      "/ownfonts/CyberCell/detail.webp"
    ],
    "order": 2
  },
  {
    "name": "PhantomWave",
    "slug": "phantomwave",
    "family": "PhantomWave",
    "hasItalic": false,
    "preview": "The quick brown fox jumps over the lazy dog",
    "desc": {
      "en": "Meine erste selbst erstellte Schrift. Eine runde Display-Schrift mit klarer Y2K-Ästhetik,  verspielt, futuristisch und prägnant.",
      "de": "My first created typeface. A rounded display font with a distinct Y2K aesthetic, playful, futuristic, and bold."
    },
    "meta": {
      "designer": "Achim Benzel",
      "version": "1.0",
      "update": "2023",
      "formats": "OTF"
    },
    "cardLabel": "Rounded",
    "downloadable": false,
    "downloadFile": null,
    "files": {
      "regular": "/ownfonts/PhantomWave/PhantomWave-Round.otf"
    },
    "images": [
      "/ownfonts/PhantomWave/weights.webp",
      "/ownfonts/PhantomWave/in-use.webp",
      "/ownfonts/PhantomWave/detail.webp"
    ],
    "order": 3
  }
];
