/* Auto-generated by build-logos.js — do not edit manually */
const LG = {
  "n-monogram": {
    "slug": "n-monogram",
    "ord": 10,
    "price": "450 €",
    "cats": [
      "logo"
    ],
    "status": "available",
    "thumb": "/logos/n-monogram/hero.webp",
    "c": "#1d3a12",
    "en": {
      "name": "N Monogram",
      "tag": "A crossed-blade N for a name starting with N",
      "desc": "A mark built from two crossing blades, cut from circles on a fixed grid so every curve has a reason. It comes as the 3D glass rendering shown here and as the flat, single-colour version, with the wordmark lockup and its clearspace already worked out. The price covers the finished mark, the source files and the right to use it commercially. Once it is sold it comes off this page, so it stays yours alone.",
      "tags": [
        "Monogram",
        "Geometric",
        "3D"
      ],
      "incl": [
        "Logo as SVG, PDF, PNG and JPG",
        "Editable Illustrator source file",
        "Light and dark versions",
        "Exclusive rights — removed from sale after purchase",
        "Colour adjusted to your brand on request"
      ]
    },
    "de": {
      "name": "N Monogramm",
      "tag": "Ein gekreuztes N für einen Namen mit N",
      "desc": "Ein Zeichen aus zwei gekreuzten Klingen, aus Kreisen auf einem festen Raster geschnitten, sodass jede Rundung einen Grund hat. Es kommt als die hier gezeigte 3D-Glasfassung und als flache, einfarbige Version, samt Wortmarken-Lockup und ausgearbeitetem Schutzraum. Der Preis umfasst das fertige Zeichen, die Quelldateien und das Recht zur kommerziellen Nutzung. Nach dem Verkauf verschwindet es von dieser Seite und gehört damit allein Ihnen.",
      "tags": [
        "Monogramm",
        "Geometrisch",
        "3D"
      ],
      "incl": [
        "Logo als SVG, PDF, PNG und JPG",
        "Bearbeitbare Illustrator-Datei",
        "Helle und dunkle Fassung",
        "Exklusiv — nach dem Kauf nicht mehr erhältlich",
        "Farbanpassung an Ihre Marke auf Wunsch"
      ]
    },
    "images": [
      {
        "src": "/logos/n-monogram/hero.webp",
        "i": 0,
        "alt": {
          "en": "The mark in green glass above the wordmark lockup",
          "de": "Das Zeichen in grünem Glas über dem Wortmarken-Lockup"
        }
      },
      {
        "src": "/logos/n-monogram/detail-01.webp",
        "i": 1,
        "alt": {
          "en": "Construction of the mark on a grid, with the circles it is built from",
          "de": "Konstruktion des Zeichens auf dem Raster, mit den zugrunde liegenden Kreisen"
        }
      },
      {
        "src": "/logos/n-monogram/detail-02.webp",
        "i": 2,
        "alt": {
          "en": "The flat lockup of mark and wordmark with its clearspace grid",
          "de": "Das flache Lockup aus Zeichen und Wortmarke mit Schutzraum-Raster"
        }
      },
      {
        "src": "/logos/n-monogram/detail-03.webp",
        "i": 3,
        "alt": {
          "en": "The logo on black business cards",
          "de": "Das Logo auf schwarzen Visitenkarten"
        }
      }
    ]
  }
};

/* ===== Universal export: works in browser AND Node (SSR). Browser ignores this. ===== */
if (typeof module !== 'undefined' && module.exports) { module.exports = { LG: LG }; }
