/* Auto-generated by build-logos.js — do not edit manually */
const LG = {
  "n-monogram": {
    "slug": "n-monogram",
    "ord": 10,
    "price": "450 €",
    "status": "available",
    "thumb": "/logos/n-monogram/hero.webp",
    "c": "#1d2b3a",
    "en": {
      "name": "N Monogram",
      "tag": "A single-letter mark for a name starting with N",
      "desc": "A geometric N built from one continuous stroke, drawn as vectors so it holds at any size and in a single colour. Ready to use as it is: the price covers the finished mark, the source files and the right to use it commercially. Once it is sold it comes off this page, so it stays yours alone.",
      "tags": [
        "Monogram",
        "Geometric",
        "One colour"
      ],
      "incl": [
        "Logo as SVG, PDF, PNG and JPG",
        "Editable Illustrator source file",
        "Light and dark versions",
        "Exclusive rights — removed from sale after purchase",
        "Colour adjusted to your brand on request"
      ]
    },
    "de": {
      "name": "N Monogramm",
      "tag": "Eine Buchstabenmarke für einen Namen mit N",
      "desc": "Ein geometrisches N aus einem durchgehenden Strich, als Vektor gezeichnet und dadurch in jeder Größe und einfarbig tragfähig. Sofort einsetzbar: Der Preis umfasst das fertige Zeichen, die Quelldateien und das Recht zur kommerziellen Nutzung. Nach dem Verkauf verschwindet es von dieser Seite und gehört damit allein Ihnen.",
      "tags": [
        "Monogramm",
        "Geometrisch",
        "Einfarbig"
      ],
      "incl": [
        "Logo als SVG, PDF, PNG und JPG",
        "Bearbeitbare Illustrator-Datei",
        "Helle und dunkle Fassung",
        "Exklusiv — nach dem Kauf nicht mehr erhältlich",
        "Farbanpassung an Ihre Marke auf Wunsch"
      ]
    },
    "images": [
      {
        "src": "/logos/n-monogram/hero.webp",
        "i": 0,
        "alt": {
          "en": "The N monogram on a plain background",
          "de": "Das N-Monogramm auf einfarbigem Hintergrund"
        }
      },
      {
        "src": "/logos/n-monogram/detail-01.webp",
        "i": 1,
        "alt": {
          "en": "The monogram in one colour, on light and on dark",
          "de": "Das Monogramm einfarbig, auf Hell und auf Dunkel"
        }
      },
      {
        "src": "/logos/n-monogram/detail-02.webp",
        "i": 2,
        "alt": {
          "en": "The monogram in use as an app icon and favicon",
          "de": "Das Monogramm als App-Icon und Favicon in der Anwendung"
        }
      }
    ]
  }
};

/* ===== Universal export: works in browser AND Node (SSR). Browser ignores this. ===== */
if (typeof module !== 'undefined' && module.exports) { module.exports = { LG: LG }; }
