/* Auto-generated by build-projects.js — do not edit manually */
const P = {
  "gute-stube": {
    "slug": "gute-stube",
    "pop": 100,
    "date": {
      "m": 8,
      "y": 2025
    },
    "yr": "2025",
    "cl": "Gute Stube",
    "cats": [
      "brand-identity"
    ],
    "thumb": "/projects/gute-stube/hero.webp",
    "c": "#101830",
    "theme": {},
    "sw": [
      {
        "name": "Adobe Illustrator",
        "icon": "/Assets/software/illustrator.svg"
      },
      {
        "name": "Adobe Photoshop",
        "icon": "/Assets/software/photoshop.svg"
      },
      {
        "name": "Miro",
        "icon": "/Assets/software/miro.svg"
      }
    ],
    "en": {
      "title": "Gute Stube Freisen",
      "type": "Client Project",
      "scope": "Brand Strategy, Visual Identity, Digital Design",
      "ind": "Gastronomy",
      "desc": "Gute Stube is a café and bistro founded in 2025 by chef Kiara Balling. What makes the bistro Gute Stube special is its focus on hearty home-style cooking and a welcoming atmosphere. The idea is to serve delicious food prepared with fresh ingredients and plenty of care, all based on traditional recipes without unnecessary frills. The goal was to reflect exactly these values in the brand identity.",
      "tags": [
        "Brand Strategy",
        "Visual Identity",
        "Digital Design"
      ]
    },
    "de": {
      "title": "Gute Stube Freisen",
      "type": "Kundenprojekt",
      "scope": "Markenstrategie, Visuelle Identität, Digital Design",
      "ind": "Gastronomie",
      "desc": "Die Gute Stube ist ein im Jahr 2025 von Köchin und Küchenmeisterin Kiara Balling gegründetes Café & Bistro in Freisen. Besonders an der Guten Stube ist, dass auf Hausmannskost sowie eine angenehme Atmosphäre gesetzt wird. Es geht darum, dass leckeres Essen mit frischen Zutaten und viel Liebe zubereitet wird. Das ganze nach traditionellen Rezepten ohne viel Schnickschnack. Ziel war es, genau diese Aspekte in der Markenidentität zu widerspiegeln.",
      "tags": [
        "Markenstrategie",
        "Visuelle Identität",
        "Digital Design"
      ]
    },
    "content": [
      {
        "type": "image",
        "src": "/projects/gute-stube/hero.webp",
        "li": 0,
        "alt": {
          "en": "Gute Stube — brand identity",
          "de": "Gute Stube — Markenidentität"
        }
      },
      {
        "type": "imageGrid",
        "images": [
          {
            "src": "/projects/gute-stube/detail-01.webp",
            "li": 1,
            "alt": {
              "en": "Gute Stube — brand application",
              "de": "Gute Stube — Markenanwendung"
            }
          },
          {
            "src": "/projects/gute-stube/detail-02.webp",
            "li": 2,
            "alt": {
              "en": "Gute Stube — brand application",
              "de": "Gute Stube — Markenanwendung"
            }
          }
        ]
      },
      {
        "type": "text",
        "variant": "center",
        "en": {
          "eyebrow": "",
          "headline": "The motto: Back to the Roots",
          "body": "To visually reflect tradition, a design approach was chosen that deliberately aims for nostalgia and timelessness. This is particularly evident in the use of a typewriter-style font, which evokes memories while also conveying a clear and minimal aesthetic. To give the menu more character and liveliness, subtle signs of wear were intentionally incorporated in the form of a fine grain texture, inspired by recipes that have been passed down through generations. At the same time, the design was reduced to the essentials in order to emphasize the underlying philosophy: the focus is on good food, not unnecessary frills."
        },
        "de": {
          "eyebrow": "",
          "headline": "Das Motto: Back to the Roots",
          "body": "Um das Traditionelle visuell widerzuspiegeln, wurde ein gestalterischer Ansatz gewählt, der bewusst auf Nostalgie und Zeitlosigkeit abzielt. Dies zeigt sich insbesondere im Einsatz einer Schreibmaschinenschrift, die Erinnerungen weckt und gleichzeitig eine klare, reduzierte Ästhetik vermittelt. Um der Speisekarte mehr Lebendigkeit zu verleihen, wurden gezielt dezente Gebrauchsspuren in Form einer feinen Körnung integriert, angelehnt an Rezepte, die über Generationen hinweg weitergegeben wurden. Gleichzeitig wurde das Design auf das Wesentliche reduziert, um die zugrunde liegende Philosophie zu unterstreichen: Im Fokus steht gutes Essen, nicht überflüssiger Schnickschnack."
        }
      },
      {
        "type": "image",
        "src": "/projects/gute-stube/detail-03.webp",
        "li": 3,
        "alt": {
          "en": "Gute Stube — menu design",
          "de": "Gute Stube — Speisekarte"
        }
      },
      {
        "type": "text",
        "en": {
          "eyebrow": "",
          "headline": "Scalable Identity System",
          "body": "To create a consistent visual identity, a distinctive design language was developed, centered around a rectangle with concave corners as its key visual element. This shape appears repeatedly in the logo, the menu frames, and the allergy icons, creating a clear visual connection across all areas of the brand. At the same time, it establishes a link to the past, as similar shapes were often used in the past for items such as tickets or labels because they served practical purposes, such as preventing dog-eared corners or making them more resistant to peeling edges when applied to curved surfaces."
        },
        "de": {
          "eyebrow": "",
          "headline": "Visuelles Identitätssystem",
          "body": "Um eine konsistente visuelle Identität zu schaffen, wurde eine eigenständige Formsprache entwickelt, deren zentrales Gestaltungselement ein Rechteck mit konkaven Ecken ist. Diese Form findet sich wiederkehrend im Logo, in den Rahmen der Speisekarten sowie in den Allergie-Icons und sorgt so für einen klaren gestalterischen Zusammenhang über alle Bereiche der Marke hinweg. Gleichzeitig schafft sie eine Verbindung zur Vergangenheit, da ähnliche Formen früher häufig bei z. B. Tickets oder Etiketten verwendet wurden. Diese hatten einen praktischen Nutzen, etwa das Verhindern von Eselsohren oder eine höhere Widerstandsfähigkeit gegen abblätternde Ränder beim Aufkleben auf gewölbten Oberflächen."
        }
      },
      {
        "type": "imageGrid",
        "images": [
          {
            "src": "/projects/gute-stube/detail-04.webp",
            "li": 4,
            "alt": {
              "en": "Gute Stube — identity system detail",
              "de": "Gute Stube — Detail des Identitätssystems"
            }
          },
          {
            "src": "/projects/gute-stube/detail-05.webp",
            "li": 5,
            "alt": {
              "en": "Gute Stube — identity system detail",
              "de": "Gute Stube — Detail des Identitätssystems"
            }
          }
        ]
      },
      {
        "type": "image",
        "src": "/projects/gute-stube/detail-06.webp",
        "li": 6,
        "alt": {
          "en": "Gute Stube — print applications",
          "de": "Gute Stube — Printanwendungen"
        }
      },
      {
        "type": "imageGrid",
        "images": [
          {
            "src": "/projects/gute-stube/detail-07.webp",
            "li": 7,
            "alt": {
              "en": "Gute Stube — print applications",
              "de": "Gute Stube — Printanwendungen"
            }
          },
          {
            "src": "/projects/gute-stube/detail-08.webp",
            "li": 8,
            "alt": {
              "en": "Gute Stube — print applications",
              "de": "Gute Stube — Printanwendungen"
            }
          }
        ]
      },
      {
        "type": "image",
        "src": "/projects/gute-stube/detail-09.webp",
        "li": 9,
        "alt": {
          "en": "Gute Stube — brand identity in use",
          "de": "Gute Stube — Markenidentität im Einsatz"
        }
      },
      {
        "type": "testimonial",
        "photo": "/projects/gute-stube/testimonial.webp",
        "name": "Kiara Balling",
        "en": {
          "role": "Owner, Gute Stube",
          "quote": "Starting a restaurant involves far more than just finding a location and creating the right dishes. Achim has been with us from day one, bringing all of our design projects to life. Not only are we thrilled with the results, our guests also notice every day how much passion and professionalism goes into everything. From the menu to the table displays and vouchers, Achim helped us create a perfectly cohesive overall concept. We are very grateful for the pleasant and reliable collaboration and look forward to all the projects still to come. Dear Achim, thank you so much for this outstanding work! We are confident that you will continue to bring many great projects to life! <3"
        },
        "de": {
          "role": "Inhaberin, Gute Stube",
          "quote": "Zu der Gründung eines Restaurants gehört deutlich mehr dazu, als eine Location zu finden und die passenden Speisen zu kreieren. Achim hat uns von Tag 1 an begleitet und alle Design-Projekte mit uns verwirklicht. Nicht nur wir selbst sind von den Ergebnissen begeistert – auch unsere Gäste merken täglich, wie viel Herzblut & Professionalität in allem steckt. Angefangen bei der Speisekarte, bis hin zu den Tischaufstellern und Gutscheinen – Achim hat uns geholfen ein perfektes Gesamtbild zu erschaffen! Wir sind sehr dankbar für die angenehme & zuverlässige Zusammenarbeit und freuen uns auf alle Projekte, die zukünftig noch anstehen. Lieber Achim, vielen Dank für diese tolle Leistung! Wir sind uns sicher, dass du noch viele großartige Projekte umsetzen wirst! <3"
        }
      }
    ],
    "imgs": [
      "/projects/gute-stube/hero.webp",
      "/projects/gute-stube/detail-01.webp",
      "/projects/gute-stube/detail-02.webp",
      "/projects/gute-stube/detail-03.webp",
      "/projects/gute-stube/detail-04.webp",
      "/projects/gute-stube/detail-05.webp",
      "/projects/gute-stube/detail-06.webp",
      "/projects/gute-stube/detail-07.webp",
      "/projects/gute-stube/detail-08.webp",
      "/projects/gute-stube/detail-09.webp"
    ]
  },
  "joeys-picknick": {
    "slug": "joeys-picknick",
    "pop": 90,
    "date": {
      "m": 1,
      "y": 2026
    },
    "yr": "2026",
    "cl": "Joeys Picknick",
    "cats": [
      "brand-identity",
      "web-design"
    ],
    "thumb": "/projects/joeys-picknick/hero.webp",
    "c": "#101830",
    "theme": {},
    "sw": [
      {
        "name": "Illustrator",
        "icon": "/Assets/software/illustrator.svg"
      },
      {
        "name": "InDesign",
        "icon": "/Assets/software/indesign.svg"
      },
      {
        "name": "Photoshop",
        "icon": "/Assets/software/photoshop.svg"
      }
    ],
    "en": {
      "title": "Joeys Picknick Mainz",
      "type": "Client Project",
      "scope": "Brand Strategy, Visual Identity, Digital Design, Website",
      "ind": "Gastronomy",
      "desc": "Joeys Picknick is a modern food truck from Mainz that specializes in renting out thoughtfully curated picnic baskets along the banks of the Rhine. What makes Joeys Picknick unique is the combination of effortless enjoyment, high-quality food, and a relaxed outdoor experience. Instead of classic street food, the focus here is on shared moments, whether with friends, family, or as a couple, right by the water.",
      "tags": [
        "Brand Strategy",
        "Visual Identity",
        "Digital Design"
      ]
    },
    "de": {
      "title": "Joeys Picknick Mainz",
      "type": "Kundenprojekt",
      "scope": "Markenstrategie, Visuelle Identität, Digital Design, Website",
      "ind": "Gastronomie",
      "desc": "Joeys Picknick ist ein moderner Foodtruck aus Mainz, der sich auf die Vermietung liebevoll zusammengestellter Picknickkörbe entlang des Rheinufers spezialisiert hat. Das Besondere an Joeys Picknick ist die Verbindung aus unkompliziertem Genuss, hochwertigem Essen und einem entspannten Outdoor-Erlebnis. Statt klassischem Streetfood steht hier das gemeinsame Erleben im Mittelpunkt, ob mit Freunden, Familie oder zu zweit, direkt am Wasser.",
      "tags": [
        "Markenstrategie",
        "Visuelle Identität",
        "Digital Design"
      ]
    },
    "content": [
      {
        "type": "image",
        "src": "/projects/joeys-picknick/hero.webp",
        "li": 0,
        "alt": {
          "en": "Joeys Picknick — brand identity",
          "de": "Joeys Picknick — Markenidentität"
        }
      },
      {
        "type": "imageGrid",
        "images": [
          {
            "src": "/projects/joeys-picknick/detail-01.webp",
            "li": 1,
            "alt": {
              "en": "Joeys Picknick — brand application",
              "de": "Joeys Picknick — Markenanwendung"
            }
          },
          {
            "src": "/projects/joeys-picknick/detail-02.webp",
            "li": 2,
            "alt": {
              "en": "Joeys Picknick — brand application",
              "de": "Joeys Picknick — Markenanwendung"
            }
          }
        ]
      },
      {
        "type": "text",
        "en": {
          "eyebrow": "Challenge",
          "headline": "Intensive process within a tight timeframe",
          "body": "The key challenge of this project was the tight schedule: a large part of the visual identity was conceived and executed within just two weeks. This compact process required fast, precise decision making and a clear design focus. The goal was to develop a cohesive, high quality brand world within a limited timeframe, one that authentically reflects the character of Joeys Picknick."
        },
        "de": {
          "eyebrow": "Challenge",
          "headline": "Intensiver Prozess auf kompaktem Zeitrahmen",
          "body": "Die besondere Herausforderung dieses Projekts lag im engen Zeitrahmen: Ein Großteil der visuellen Identität wurde innerhalb von nur zwei Wochen konzipiert und umgesetzt. Dieser kompakte Prozess erforderte schnelle, präzise Entscheidungen sowie einen klaren gestalterischen Fokus. Ziel war es, trotz des kurzen Zeitfensters eine stimmige und hochwertige Markenwelt zu entwickeln, die den Charakter von Joeys Picknick authentisch widerspiegelt."
        }
      },
      {
        "type": "image",
        "src": "/projects/joeys-picknick/detail-03.webp",
        "li": 3,
        "alt": {
          "en": "Joeys Picknick — brand application",
          "de": "Joeys Picknick — Markenanwendung"
        }
      },
      {
        "type": "imageGrid",
        "images": [
          {
            "src": "/projects/joeys-picknick/detail-04.webp",
            "li": 4,
            "alt": {
              "en": "Joeys Picknick — brand application",
              "de": "Joeys Picknick — Markenanwendung"
            }
          },
          {
            "src": "/projects/joeys-picknick/detail-05.webp",
            "li": 5,
            "alt": {
              "en": "Joeys Picknick — brand application",
              "de": "Joeys Picknick — Markenanwendung"
            }
          }
        ]
      },
      {
        "type": "image",
        "src": "/projects/joeys-picknick/detail-06.webp",
        "li": 6,
        "alt": {
          "en": "Joeys Picknick — brand application",
          "de": "Joeys Picknick — Markenanwendung"
        }
      },
      {
        "type": "testimonial",
        "photo": "/projects/joeys-picknick/testimonial.webp",
        "name": "Joël Espenschied",
        "en": {
          "role": "Owner, Joeys Picknick",
          "quote": "I had already worked with Achim during my studies, so it quickly became clear to me that he was the right partner for the design of Joeys Picknick. He developed the entire visual identity, from the logo and website to menus and flyers. What stands out in particular is his deep understanding of my concept, as well as the professional yet straightforward collaboration. He actively contributed ideas, handled feedback constructively at all times, and reliably met every deadline. A clear recommendation for anyone who values well-thought-out, high-quality design."
        },
        "de": {
          "role": "Inhaber, Joeys Picknick",
          "quote": "Mit Achim habe ich bereits im Studium zusammengearbeitet, weshalb mir schnell klar war, dass er der richtige Partner für das Design von Joeys Picknick ist. Er hat das komplette Erscheinungsbild entwickelt – von Logo und Website bis hin zu Speisekarten und Flyern. Besonders hervorzuheben ist sein tiefes Verständnis für mein Konzept sowie die professionelle und gleichzeitig unkomplizierte Zusammenarbeit. Er hat aktiv mitgedacht, Feedback jederzeit konstruktiv aufgenommen und alle Deadlines zuverlässig eingehalten. Eine klare Empfehlung für alle, die Wert auf durchdachtes und hochwertiges Design legen."
        }
      }
    ],
    "imgs": [
      "/projects/joeys-picknick/hero.webp",
      "/projects/joeys-picknick/detail-01.webp",
      "/projects/joeys-picknick/detail-02.webp",
      "/projects/joeys-picknick/detail-03.webp",
      "/projects/joeys-picknick/detail-04.webp",
      "/projects/joeys-picknick/detail-05.webp",
      "/projects/joeys-picknick/detail-06.webp"
    ]
  },
  "lumakeys": {
    "slug": "lumakeys",
    "pop": 85,
    "date": {
      "m": 6,
      "y": 2026
    },
    "yr": "2026",
    "cl": "LumaKeys",
    "cats": [
      "logo-design"
    ],
    "thumb": "/projects/lumakeys/hero.webp",
    "c": "#3d1155",
    "theme": {},
    "sw": [
      {
        "name": "Illustrator",
        "icon": "/Assets/software/illustrator.svg"
      }
    ],
    "en": {
      "title": "LumaKeys",
      "type": "Client Project",
      "scope": "Logo Design, Wordmark, Icon Design",
      "ind": "Music Education / App",
      "desc": "A logo and wordmark for LumaKeys, a piano-learning app at lumakeys.app that teaches with falling notes running into a keyboard, Synthesia-style. The mark takes that idea literally: three keys caught mid-strike, drawn so they still read as keys at favicon size.",
      "tags": [
        "Logo Design",
        "Wordmark",
        "App Icon"
      ]
    },
    "de": {
      "title": "LumaKeys",
      "type": "Kundenprojekt",
      "scope": "Logo Design, Wortmarke, Icon Design",
      "ind": "Musikbildung / App",
      "desc": "Logo und Wortmarke für LumaKeys, eine Klavier-Lern-App unter lumakeys.app, die im Synthesia-Stil mit herablaufenden Noten auf eine Klaviatur unterrichtet. Das Zeichen nimmt genau das auf: drei Tasten im Anschlag, so gezeichnet, dass sie auch in Favicon-Größe noch als Tasten lesbar sind.",
      "tags": [
        "Logo Design",
        "Wortmarke",
        "App Icon"
      ]
    },
    "content": [
      {
        "type": "image",
        "src": "/projects/lumakeys/hero.webp",
        "li": 0,
        "alt": {
          "en": "LumaKeys logo and wordmark in white on a purple gradient",
          "de": "LumaKeys Logo und Wortmarke in Weiß auf violettem Verlauf"
        }
      },
      {
        "type": "text",
        "variant": "center",
        "en": {
          "eyebrow": "Challenge",
          "headline": "A piano app that looks like a piano app",
          "body": "LumaKeys teaches piano the way Synthesia does — notes fall down the screen and land on a keyboard. The identity had to carry that motion in a still image, without ending up as another generic music note, and without leaning on the app screenshot to be understood. It also had to survive being 16 pixels wide in a browser tab."
        },
        "de": {
          "eyebrow": "Herausforderung",
          "headline": "Eine Klavier-App, die nach Klavier-App aussieht",
          "body": "LumaKeys bringt Klavier so bei wie Synthesia — Noten laufen den Bildschirm herunter und landen auf einer Klaviatur. Die Identität musste diese Bewegung im Standbild transportieren, ohne als weitere generische Note zu enden und ohne den App-Screenshot zu brauchen, um verstanden zu werden. Und sie musste 16 Pixel breit im Browser-Tab noch bestehen."
        }
      },
      {
        "type": "image",
        "src": "/projects/lumakeys/detail-01.webp",
        "li": 1,
        "alt": {
          "en": "LumaKeys mark in black on light and white on dark",
          "de": "LumaKeys-Zeichen in Schwarz auf Hell und Weiß auf Dunkel"
        }
      },
      {
        "type": "image",
        "src": "/projects/lumakeys/detail-02.webp",
        "li": 2,
        "alt": {
          "en": "LumaKeys lockup with clearspace and construction guides",
          "de": "LumaKeys-Lockup mit Schutzraum und Konstruktionslinien"
        }
      },
      {
        "type": "image",
        "src": "/projects/lumakeys/detail-03.webp",
        "li": 3,
        "alt": {
          "en": "LumaKeys app icon and browser favicon in use",
          "de": "LumaKeys App-Icon und Browser-Favicon in der Anwendung"
        }
      },
      {
        "type": "text",
        "variant": "center",
        "en": {
          "eyebrow": "Outcome",
          "headline": "Three keys caught mid-strike",
          "body": "One shape, repeated three times and staggered in depth, reads as keys being struck in sequence — the falling-note motion frozen into a mark. Built from a handful of vector paths in Illustrator, so the same file is the app icon, the favicon and the full-width brand board. Nothing had to be simplified for the small sizes."
        },
        "de": {
          "eyebrow": "Ergebnis",
          "headline": "Drei Tasten im Anschlag",
          "body": "Eine Form, dreifach wiederholt und in der Tiefe versetzt, liest sich als nacheinander angeschlagene Tasten — die Bewegung der fallenden Noten im Zeichen eingefroren. Aus wenigen Vektorpfaden in Illustrator gebaut, sodass dieselbe Datei App-Icon, Favicon und vollflächiges Markenbild trägt. Für die kleinen Größen musste nichts vereinfacht werden."
        }
      },
      {
        "type": "testimonial",
        "photo": "/projects/lumakeys/testimonial.webp",
        "name": "Ramon Melchior",
        "en": {
          "role": "Founder, LumaKeys",
          "quote": "To take the visual design of my piano app to the next level and help it live up to its full potential, I was looking for a designer who could translate my ideas, wishes, and requirements into professional designs. I quickly came across Achim, and within just a few days, I received a high-quality logo along with a wide range of marketing assets. In addition, he regularly provides valuable feedback on how both my website and product can be further improved from a visual and customer perspective. I look forward to continuing to work with Achim!"
        },
        "de": {
          "role": "Gründer, LumaKeys",
          "quote": "Um meine Piano App optisch auf ein neues Level zu bringen und ihrem Potenzial gerecht zu werden, war ich auf der Suche nach einem Designer der meine Ideen, Wünsche und Anforderungen in professionelle Designs übersetzen kann. Ich bin schnell auf Achim gestoßen und habe innerhalb weniger Tage ein hochwertiges Logo sowie verschiedenste Marketing-Assets erhalten. Darüber hinaus bekomme ich regelmäßig wertvolles Feedback, wie meine Website und mein Produkt sowohl optisch als auch aus Kundensicht weiter aufgewertet werden können. Ich freue mich auf die weitere Zusammenarbeit mit Achim!"
        }
      }
    ],
    "imgs": [
      "/projects/lumakeys/hero.webp",
      "/projects/lumakeys/detail-01.webp",
      "/projects/lumakeys/detail-02.webp",
      "/projects/lumakeys/detail-03.webp"
    ]
  },
  "plantup-logo-animation": {
    "slug": "plantup-logo-animation",
    "pop": 77,
    "date": {
      "m": 10,
      "y": 2026
    },
    "yr": "2026",
    "cl": "Malte Lehmann",
    "cats": [
      "motion-design",
      "logo-design"
    ],
    "thumb": "/projects/plant-up/hero.webp",
    "c": "#12351d",
    "theme": {},
    "sw": [
      {
        "name": "Adobe Illustrator",
        "icon": "/Assets/software/illustrator.svg"
      },
      {
        "name": "Adobe After Effects",
        "icon": "/Assets/software/after-effects.svg"
      }
    ],
    "en": {
      "title": "PlantUp",
      "type": "Client Project",
      "scope": "Logo Design, Icon Design, Logo Animation",
      "ind": "Games, Indie Game, Entertainment",
      "desc": "PlantUp is a game by Malte Lehmann for which a logo was designed and animated. The project was set up as a compact one-shot, focused on developing a fitting visual logo idea for the game and then translating it into a short and a longer animated version.",
      "tags": [
        "Logo Design",
        "Logo Animation",
        "Icon Design",
        "Motion Design",
        "Game Design"
      ]
    },
    "de": {
      "title": "PlantUp",
      "type": "Kundenprojekt",
      "scope": "Logo Design, Icon Design, Logo Animation",
      "ind": "Games, Indie Game, Entertainment",
      "desc": "PlantUp ist ein Spiel von Malte Lehmann, für das ein Logo entwickelt und animiert wurde. Das Projekt war als kompakte Umsetzung angelegt und konzentrierte sich darauf, eine passende visuelle Logoidee für das Spiel zu gestalten und diese anschließend in eine kurze und eine längere Animationsversion zu übertragen.",
      "tags": [
        "Logo Design",
        "Logo Animation",
        "Icon Design",
        "Motion Design",
        "Game Design"
      ]
    },
    "content": [
      {
        "type": "image",
        "src": "/projects/plant-up/hero.webp",
        "li": 0,
        "alt": {
          "en": "PlantUp — logo",
          "de": "PlantUp — Logo"
        }
      },
      {
        "type": "video",
        "src": "/projects/plant-up/animation.mp4",
        "poster": "/projects/plant-up/animation.webp",
        "title": "PlantUp — Logo Animation"
      },
      {
        "type": "imageGrid",
        "images": [
          {
            "src": "/projects/plant-up/detail-02.webp",
            "li": 1,
            "alt": {
              "en": "PlantUp — plant icons",
              "de": "PlantUp — Pflanzen Icons"
            }
          },
          {
            "src": "/projects/plant-up/detail-03.webp",
            "li": 2,
            "alt": {
              "en": "PlantUp — logo elements and layers",
              "de": "PlantUp — Logo Elemente und Ebenen"
            }
          }
        ]
      },
      {
        "type": "image",
        "src": "/projects/plant-up/detail-04.webp",
        "li": 3,
        "alt": {
          "en": "PlantUp — logo animation",
          "de": "PlantUp — Logo Animation"
        }
      },
      {
        "type": "imageGrid",
        "images": [
          {
            "src": "/projects/plant-up/detail-06.gif",
            "li": 4,
            "alt": {
              "en": "PlantUp — animated version, detail",
              "de": "PlantUp — Animationsversion Detail"
            }
          },
          {
            "src": "/projects/plant-up/detail-07.webp",
            "li": 5,
            "alt": {
              "en": "PlantUp — long logo animation",
              "de": "PlantUp — Lange Logo Animation"
            }
          }
        ]
      },
      {
        "type": "image",
        "src": "/projects/plant-up/detail-05.webp",
        "li": 6,
        "alt": {
          "en": "PlantUp — final application",
          "de": "PlantUp — Finale Anwendung"
        }
      },
      {
        "type": "testimonial",
        "photo": "/projects/plant-up/testimonial.webp",
        "name": "Malte Lehmann",
        "en": {
          "role": "PlantUp",
          "quote": "Placeholder text — will be added later."
        },
        "de": {
          "role": "PlantUp",
          "quote": "Platzhaltertext — wird später hinzugefügt."
        }
      }
    ],
    "imgs": [
      "/projects/plant-up/hero.webp",
      "/projects/plant-up/detail-02.webp",
      "/projects/plant-up/detail-03.webp",
      "/projects/plant-up/detail-04.webp",
      "/projects/plant-up/detail-06.gif",
      "/projects/plant-up/detail-07.webp",
      "/projects/plant-up/detail-05.webp"
    ]
  },
  "euphorik-berlin": {
    "slug": "euphorik-berlin",
    "pop": 75,
    "date": {
      "m": 9,
      "y": 2024
    },
    "yr": "2024",
    "cl": "Euphorik Berlin",
    "cats": [
      "logo-design"
    ],
    "thumb": "/projects/euphorik-berlin/hero.webp",
    "c": "#3a0f14",
    "theme": {},
    "sw": [
      {
        "name": "Illustrator",
        "icon": "/Assets/software/illustrator.svg"
      },
      {
        "name": "Blender",
        "icon": "/Assets/software/blender.svg"
      }
    ],
    "en": {
      "title": "Euphorik Berlin",
      "type": "Client Project",
      "scope": "Logo Design, Wordmark",
      "ind": "Music / Nightlife",
      "desc": "A logo and wordmark for Euphorik Berlin, a DJ act from the Berlin club scene. The mark had to survive the places a DJ logo actually lives: a small avatar on a streaming platform, a corner of a flyer, a projection behind the booth. One shape, drawn as vectors in Illustrator, that stays recognisable at every one of those sizes.",
      "tags": [
        "Logo Design",
        "Wordmark",
        "Music"
      ]
    },
    "de": {
      "title": "Euphorik Berlin",
      "type": "Kundenprojekt",
      "scope": "Logo Design, Wortmarke",
      "ind": "Musik / Nightlife",
      "desc": "Logo und Wortmarke für Euphorik Berlin, ein DJ-Act aus der Berliner Clubszene. Das Zeichen musste dort bestehen, wo ein DJ-Logo tatsächlich auftaucht: als kleines Avatar auf einer Streaming-Plattform, in der Ecke eines Flyers, als Projektion hinter dem Pult. Eine Form, als Vektor in Illustrator gezeichnet, die in jeder dieser Größen erkennbar bleibt.",
      "tags": [
        "Logo Design",
        "Wortmarke",
        "Musik"
      ]
    },
    "content": [
      {
        "type": "image",
        "src": "/projects/euphorik-berlin/hero.webp",
        "li": 0,
        "alt": {
          "en": "Euphorik Berlin logo and wordmark",
          "de": "Euphorik Berlin Logo und Wortmarke"
        }
      },
      {
        "type": "image",
        "src": "/projects/euphorik-berlin/detail-01.webp",
        "li": 1,
        "alt": {
          "en": "Euphorik Berlin mark in black on light and white on dark",
          "de": "Euphorik-Berlin-Zeichen in Schwarz auf Hell und Weiß auf Dunkel"
        }
      },
      {
        "type": "image",
        "src": "/projects/euphorik-berlin/detail-02.webp",
        "li": 2,
        "alt": {
          "en": "Euphorik Berlin lockup with clearspace and construction guides",
          "de": "Euphorik-Berlin-Lockup mit Schutzraum und Konstruktionslinien"
        }
      },
      {
        "type": "image",
        "src": "/projects/euphorik-berlin/detail-03.webp",
        "li": 3,
        "alt": {
          "en": "Euphorik Berlin mark used as an avatar and on cover artwork",
          "de": "Euphorik-Berlin-Zeichen als Avatar und auf Cover-Artwork"
        }
      }
    ],
    "imgs": [
      "/projects/euphorik-berlin/hero.webp",
      "/projects/euphorik-berlin/detail-01.webp",
      "/projects/euphorik-berlin/detail-02.webp",
      "/projects/euphorik-berlin/detail-03.webp"
    ]
  }
};

/* ===== Universal export: works in browser AND Node (SSR). Browser ignores this. ===== */
if (typeof module !== 'undefined' && module.exports) { module.exports = { P: P }; }
