/* Auto-generated by build-projects.js — do not edit manually */
const P = {
  "gute-stube": {
    "slug": "gute-stube",
    "pop": 100,
    "date": {
      "m": 8,
      "y": 2025
    },
    "yr": "2025",
    "cl": "Gute Stube",
    "cats": [
      "brand-identity"
    ],
    "thumb": "/projects/gute-stube/hero.webp",
    "c": "#101830",
    "theme": {},
    "sw": [
      {
        "name": "Adobe Illustrator",
        "icon": "/Assets/software/illustrator.svg"
      },
      {
        "name": "Adobe Photoshop",
        "icon": "/Assets/software/photoshop.svg"
      },
      {
        "name": "Miro",
        "icon": "/Assets/software/miro.svg"
      }
    ],
    "en": {
      "title": "Gute Stube Freisen",
      "type": "Client Project",
      "scope": "Brand Strategy, Visual Identity, Digital Design",
      "ind": "Gastronomy",
      "desc": "Gute Stube is a café and bistro founded in 2025 by chef Kiara Balling. What makes the bistro Gute Stube special is its focus on hearty home-style cooking and a welcoming atmosphere. The idea is to serve delicious food prepared with fresh ingredients and plenty of care, all based on traditional recipes without unnecessary frills. The goal was to reflect exactly these values in the brand identity.",
      "tags": [
        "Brand Strategy",
        "Visual Identity",
        "Digital Design"
      ]
    },
    "de": {
      "title": "Gute Stube Freisen",
      "type": "Kundenprojekt",
      "scope": "Markenstrategie, Visuelle Identität, Digital Design",
      "ind": "Gastronomie",
      "desc": "Die Gute Stube ist ein im Jahr 2025 von Köchin und Küchenmeisterin Kiara Balling gegründetes Café & Bistro in Freisen. Besonders an der Guten Stube ist, dass auf Hausmannskost sowie eine angenehme Atmosphäre gesetzt wird. Es geht darum, dass leckeres Essen mit frischen Zutaten und viel Liebe zubereitet wird. Das ganze nach traditionellen Rezepten ohne viel Schnickschnack. Ziel war es, genau diese Aspekte in der Markenidentität zu widerspiegeln.",
      "tags": [
        "Markenstrategie",
        "Visuelle Identität",
        "Digital Design"
      ]
    },
    "content": [
      {
        "type": "image",
        "src": "/projects/gute-stube/hero.webp",
        "li": 0,
        "alt": {
          "en": "Gute Stube — brand identity",
          "de": "Gute Stube — Markenidentität"
        }
      },
      {
        "type": "imageGrid",
        "images": [
          {
            "src": "/projects/gute-stube/detail-01.webp",
            "li": 1,
            "alt": {
              "en": "Gute Stube — brand application",
              "de": "Gute Stube — Markenanwendung"
            }
          },
          {
            "src": "/projects/gute-stube/detail-02.webp",
            "li": 2,
            "alt": {
              "en": "Gute Stube — brand application",
              "de": "Gute Stube — Markenanwendung"
            }
          }
        ]
      },
      {
        "type": "text",
        "variant": "center",
        "en": {
          "eyebrow": "",
          "headline": "The motto: Back to the Roots",
          "body": "To visually reflect tradition, a design approach was chosen that deliberately aims for nostalgia and timelessness. This is particularly evident in the use of a typewriter-style font, which evokes memories while also conveying a clear and minimal aesthetic. To give the menu more character and liveliness, subtle signs of wear were intentionally incorporated in the form of a fine grain texture, inspired by recipes that have been passed down through generations. At the same time, the design was reduced to the essentials in order to emphasize the underlying philosophy: the focus is on good food, not unnecessary frills."
        },
        "de": {
          "eyebrow": "",
          "headline": "Das Motto: Back to the Roots",
          "body": "Um das Traditionelle visuell widerzuspiegeln, wurde ein gestalterischer Ansatz gewählt, der bewusst auf Nostalgie und Zeitlosigkeit abzielt. Dies zeigt sich insbesondere im Einsatz einer Schreibmaschinenschrift, die Erinnerungen weckt und gleichzeitig eine klare, reduzierte Ästhetik vermittelt. Um der Speisekarte mehr Lebendigkeit zu verleihen, wurden gezielt dezente Gebrauchsspuren in Form einer feinen Körnung integriert, angelehnt an Rezepte, die über Generationen hinweg weitergegeben wurden. Gleichzeitig wurde das Design auf das Wesentliche reduziert, um die zugrunde liegende Philosophie zu unterstreichen: Im Fokus steht gutes Essen, nicht überflüssiger Schnickschnack."
        }
      },
      {
        "type": "image",
        "src": "/projects/gute-stube/detail-03.webp",
        "li": 3,
        "alt": {
          "en": "Gute Stube — menu design",
          "de": "Gute Stube — Speisekarte"
        }
      },
      {
        "type": "text",
        "en": {
          "eyebrow": "",
          "headline": "Scalable Identity System",
          "body": "To create a consistent visual identity, a distinctive design language was developed, centered around a rectangle with concave corners as its key visual element. This shape appears repeatedly in the logo, the menu frames, and the allergy icons, creating a clear visual connection across all areas of the brand. At the same time, it establishes a link to the past, as similar shapes were often used in the past for items such as tickets or labels because they served practical purposes, such as preventing dog-eared corners or making them more resistant to peeling edges when applied to curved surfaces."
        },
        "de": {
          "eyebrow": "",
          "headline": "Visuelles Identitätssystem",
          "body": "Um eine konsistente visuelle Identität zu schaffen, wurde eine eigenständige Formsprache entwickelt, deren zentrales Gestaltungselement ein Rechteck mit konkaven Ecken ist. Diese Form findet sich wiederkehrend im Logo, in den Rahmen der Speisekarten sowie in den Allergie-Icons und sorgt so für einen klaren gestalterischen Zusammenhang über alle Bereiche der Marke hinweg. Gleichzeitig schafft sie eine Verbindung zur Vergangenheit, da ähnliche Formen früher häufig bei z. B. Tickets oder Etiketten verwendet wurden. Diese hatten einen praktischen Nutzen, etwa das Verhindern von Eselsohren oder eine höhere Widerstandsfähigkeit gegen abblätternde Ränder beim Aufkleben auf gewölbten Oberflächen."
        }
      },
      {
        "type": "imageGrid",
        "images": [
          {
            "src": "/projects/gute-stube/detail-04.webp",
            "li": 4,
            "alt": {
              "en": "Gute Stube — identity system detail",
              "de": "Gute Stube — Detail des Identitätssystems"
            }
          },
          {
            "src": "/projects/gute-stube/detail-05.webp",
            "li": 5,
            "alt": {
              "en": "Gute Stube — identity system detail",
              "de": "Gute Stube — Detail des Identitätssystems"
            }
          }
        ]
      },
      {
        "type": "image",
        "src": "/projects/gute-stube/detail-06.webp",
        "li": 6,
        "alt": {
          "en": "Gute Stube — print applications",
          "de": "Gute Stube — Printanwendungen"
        }
      },
      {
        "type": "imageGrid",
        "images": [
          {
            "src": "/projects/gute-stube/detail-07.webp",
            "li": 7,
            "alt": {
              "en": "Gute Stube — print applications",
              "de": "Gute Stube — Printanwendungen"
            }
          },
          {
            "src": "/projects/gute-stube/detail-08.webp",
            "li": 8,
            "alt": {
              "en": "Gute Stube — print applications",
              "de": "Gute Stube — Printanwendungen"
            }
          }
        ]
      },
      {
        "type": "image",
        "src": "/projects/gute-stube/detail-09.webp",
        "li": 9,
        "alt": {
          "en": "Gute Stube — brand identity in use",
          "de": "Gute Stube — Markenidentität im Einsatz"
        }
      },
      {
        "type": "testimonial",
        "photo": "/projects/gute-stube/testimonial.webp",
        "name": "Kiara Balling",
        "en": {
          "role": "Owner",
          "quote": "Starting a restaurant involves far more than just finding a location and creating the right dishes. Achim has been with us from day one, bringing all of our design projects to life. Not only are we thrilled with the results, our guests also notice every day how much passion and professionalism goes into everything. From the menu to the table displays and vouchers, Achim helped us create a perfectly cohesive overall concept. We are very grateful for the pleasant and reliable collaboration and look forward to all the projects still to come. Dear Achim, thank you so much for this outstanding work! We are confident that you will continue to bring many great projects to life! <3"
        },
        "de": {
          "role": "Inhaberin",
          "quote": "Zu der Gründung eines Restaurants gehört deutlich mehr dazu, als eine Location zu finden und die passenden Speisen zu kreieren. Achim hat uns von Tag 1 an begleitet und alle Design-Projekte mit uns verwirklicht. Nicht nur wir selbst sind von den Ergebnissen begeistert – auch unsere Gäste merken täglich, wie viel Herzblut & Professionalität in allem steckt. Angefangen bei der Speisekarte, bis hin zu den Tischaufstellern und Gutscheinen – Achim hat uns geholfen ein perfektes Gesamtbild zu erschaffen! Wir sind sehr dankbar für die angenehme & zuverlässige Zusammenarbeit und freuen uns auf alle Projekte, die zukünftig noch anstehen. Lieber Achim, vielen Dank für diese tolle Leistung! Wir sind uns sicher, dass du noch viele großartige Projekte umsetzen wirst! <3"
        }
      }
    ],
    "imgs": [
      "/projects/gute-stube/hero.webp",
      "/projects/gute-stube/detail-01.webp",
      "/projects/gute-stube/detail-02.webp",
      "/projects/gute-stube/detail-03.webp",
      "/projects/gute-stube/detail-04.webp",
      "/projects/gute-stube/detail-05.webp",
      "/projects/gute-stube/detail-06.webp",
      "/projects/gute-stube/detail-07.webp",
      "/projects/gute-stube/detail-08.webp",
      "/projects/gute-stube/detail-09.webp"
    ]
  },
  "joeys-picknick": {
    "slug": "joeys-picknick",
    "pop": 90,
    "date": {
      "m": 1,
      "y": 2026
    },
    "yr": "2026",
    "cl": "Joeys Picknick",
    "cats": [
      "brand-identity"
    ],
    "thumb": "/projects/joeys-picknick/hero.webp",
    "c": "#101830",
    "theme": {},
    "sw": [],
    "en": {
      "title": "Joeys Picknick Mainz",
      "type": "Client Project",
      "scope": "Brand Strategy, Visual Identity, Digital Design",
      "ind": "Gastronomy",
      "desc": "Joeys Picknick is a modern food truck from Mainz that specializes in renting out thoughtfully curated picnic baskets along the banks of the Rhine. What makes Joeys Picknick unique is the combination of effortless enjoyment, high-quality food, and a relaxed outdoor experience. Instead of classic street food, the focus here is on shared moments, whether with friends, family, or as a couple, right by the water.",
      "tags": [
        "Brand Strategy",
        "Visual Identity",
        "Digital Design"
      ]
    },
    "de": {
      "title": "Joeys Picknick Mainz",
      "type": "Kundenprojekt",
      "scope": "Markenstrategie, Visuelle Identität, Digital Design",
      "ind": "Gastronomie",
      "desc": "Joeys Picknick ist ein moderner Foodtruck aus Mainz, der sich auf die Vermietung liebevoll zusammengestellter Picknickkörbe entlang des Rheinufers spezialisiert hat. Das Besondere an Joeys Picknick ist die Verbindung aus unkompliziertem Genuss, hochwertigem Essen und einem entspannten Outdoor-Erlebnis. Statt klassischem Streetfood steht hier das gemeinsame Erleben im Mittelpunkt, ob mit Freunden, Familie oder zu zweit, direkt am Wasser.",
      "tags": [
        "Markenstrategie",
        "Visuelle Identität",
        "Digital Design"
      ]
    },
    "content": [
      {
        "type": "image",
        "src": "/projects/joeys-picknick/hero.webp",
        "li": 0,
        "alt": {
          "en": "Joeys Picknick — brand identity",
          "de": "Joeys Picknick — Markenidentität"
        }
      },
      {
        "type": "imageGrid",
        "images": [
          {
            "src": "/projects/joeys-picknick/detail-01.webp",
            "li": 1,
            "alt": {
              "en": "Joeys Picknick — brand application",
              "de": "Joeys Picknick — Markenanwendung"
            }
          },
          {
            "src": "/projects/joeys-picknick/detail-02.webp",
            "li": 2,
            "alt": {
              "en": "Joeys Picknick — brand application",
              "de": "Joeys Picknick — Markenanwendung"
            }
          }
        ]
      },
      {
        "type": "text",
        "en": {
          "eyebrow": "Challenge",
          "headline": "Intensive process within a tight timeframe",
          "body": "The key challenge of this project was the tight schedule: a large part of the visual identity was conceived and executed within just two weeks. This compact process required fast, precise decision making and a clear design focus. The goal was to develop a cohesive, high quality brand world within a limited timeframe, one that authentically reflects the character of Joeys Picknick."
        },
        "de": {
          "eyebrow": "Challenge",
          "headline": "Intensiver Prozess auf kompaktem Zeitrahmen",
          "body": "Die besondere Herausforderung dieses Projekts lag im engen Zeitrahmen: Ein Großteil der visuellen Identität wurde innerhalb von nur zwei Wochen konzipiert und umgesetzt. Dieser kompakte Prozess erforderte schnelle, präzise Entscheidungen sowie einen klaren gestalterischen Fokus. Ziel war es, trotz des kurzen Zeitfensters eine stimmige und hochwertige Markenwelt zu entwickeln, die den Charakter von Joeys Picknick authentisch widerspiegelt."
        }
      },
      {
        "type": "image",
        "src": "/projects/joeys-picknick/detail-03.webp",
        "li": 3,
        "alt": {
          "en": "Joeys Picknick — brand application",
          "de": "Joeys Picknick — Markenanwendung"
        }
      },
      {
        "type": "imageGrid",
        "images": [
          {
            "src": "/projects/joeys-picknick/detail-04.webp",
            "li": 4,
            "alt": {
              "en": "Joeys Picknick — brand application",
              "de": "Joeys Picknick — Markenanwendung"
            }
          },
          {
            "src": "/projects/joeys-picknick/detail-05.webp",
            "li": 5,
            "alt": {
              "en": "Joeys Picknick — brand application",
              "de": "Joeys Picknick — Markenanwendung"
            }
          }
        ]
      },
      {
        "type": "testimonial",
        "photo": "/projects/joeys-picknick/testimonial.webp",
        "name": "Joël Espenschied",
        "en": {
          "role": "Owner",
          "quote": "I had already worked with Achim during my studies, so it quickly became clear to me that he was the right partner for the design of Joeys Picknick. He developed the entire visual identity, from the logo and website to menus and flyers. What stands out in particular is his deep understanding of my concept, as well as the professional yet straightforward collaboration. He actively contributed ideas, handled feedback constructively at all times, and reliably met every deadline. A clear recommendation for anyone who values well-thought-out, high-quality design."
        },
        "de": {
          "role": "Inhaber",
          "quote": "Mit Achim habe ich bereits im Studium zusammengearbeitet, weshalb mir schnell klar war, dass er der richtige Partner für das Design von Joeys Picknick ist. Er hat das komplette Erscheinungsbild entwickelt – von Logo und Website bis hin zu Speisekarten und Flyern. Besonders hervorzuheben ist sein tiefes Verständnis für mein Konzept sowie die professionelle und gleichzeitig unkomplizierte Zusammenarbeit. Er hat aktiv mitgedacht, Feedback jederzeit konstruktiv aufgenommen und alle Deadlines zuverlässig eingehalten. Eine klare Empfehlung für alle, die Wert auf durchdachtes und hochwertiges Design legen."
        }
      }
    ],
    "imgs": [
      "/projects/joeys-picknick/hero.webp",
      "/projects/joeys-picknick/detail-01.webp",
      "/projects/joeys-picknick/detail-02.webp",
      "/projects/joeys-picknick/detail-03.webp",
      "/projects/joeys-picknick/detail-04.webp",
      "/projects/joeys-picknick/detail-05.webp"
    ]
  },
  "logo-types": {
    "slug": "logo-types",
    "pop": 80,
    "date": {
      "m": 12,
      "y": 2025
    },
    "yr": "2024 - 2025",
    "cl": "Multiple",
    "cats": [
      "3d-design",
      "brand-identity"
    ],
    "thumb": "/projects/logo-types/hero.webp",
    "c": "#1a2e1a",
    "theme": {},
    "sw": [],
    "en": {
      "title": "Logos & Custom Typography",
      "type": "Client Projects",
      "scope": "Logo Design, 3D Logo Design, 3D Logo Animation",
      "ind": "Music & Streetwear",
      "desc": "A curated selection of logo and 3D logo designs from 2024–2025. The work explores a range of visual approaches. From clean, minimal marks to more experimental designs.",
      "tags": [
        "Logo Design",
        "3D Design",
        "Logo Animation"
      ]
    },
    "de": {
      "title": "Logos & Custom Typografie",
      "type": "Kundenprojekte",
      "scope": "Logo Design, 3D Logo Design, 3D Logo Animation",
      "ind": "Musik & Streetwear",
      "desc": "Eine kuratierte Auswahl an Logo- und 3D-Logo-Designs aus den Jahren 2024–2025. Die Arbeiten zeigen unterschiedliche visuelle Ansätze. Von klaren, reduzierten Markenzeichen bis hin zu experimentellen Gestaltungen.",
      "tags": [
        "Logo Design",
        "3D Design",
        "Logo Animation"
      ]
    },
    "content": [
      {
        "type": "text",
        "en": {
          "eyebrow": "Selection",
          "headline": "2D & 3D Logos",
          "body": ""
        },
        "de": {
          "eyebrow": "Auswahl",
          "headline": "2D & 3D Logos",
          "body": ""
        }
      },
      {
        "type": "image",
        "src": "/projects/logo-types/detail-01.webp",
        "li": 0,
        "alt": {
          "en": "Logo design — selected work",
          "de": "Logo Design — Auswahlarbeit"
        }
      },
      {
        "type": "imageGrid",
        "images": [
          {
            "src": "/projects/logo-types/detail-02.webp",
            "li": 1,
            "alt": {
              "en": "Logo design — selected work",
              "de": "Logo Design — Auswahlarbeit"
            }
          },
          {
            "src": "/projects/logo-types/detail-03.webp",
            "li": 2,
            "alt": {
              "en": "Logo design — selected work",
              "de": "Logo Design — Auswahlarbeit"
            }
          }
        ]
      },
      {
        "type": "image",
        "src": "/projects/logo-types/detail-04.webp",
        "li": 3,
        "alt": {
          "en": "Logo design — selected work",
          "de": "Logo Design — Auswahlarbeit"
        }
      },
      {
        "type": "imageGrid",
        "images": [
          {
            "src": "/projects/logo-types/detail-05.webp",
            "li": 4,
            "alt": {
              "en": "Logo design — selected work",
              "de": "Logo Design — Auswahlarbeit"
            }
          },
          {
            "src": "/projects/logo-types/detail-06.webp",
            "li": 5,
            "alt": {
              "en": "Logo design — selected work",
              "de": "Logo Design — Auswahlarbeit"
            }
          }
        ]
      },
      {
        "type": "image",
        "src": "/projects/logo-types/detail-07.webp",
        "li": 6,
        "alt": {
          "en": "Logo design — selected work",
          "de": "Logo Design — Auswahlarbeit"
        }
      },
      {
        "type": "imageGrid",
        "images": [
          {
            "src": "/projects/logo-types/detail-08.webp",
            "li": 7,
            "alt": {
              "en": "Logo design — selected work",
              "de": "Logo Design — Auswahlarbeit"
            }
          },
          {
            "src": "/projects/logo-types/detail-09.webp",
            "li": 8,
            "alt": {
              "en": "Logo design — selected work",
              "de": "Logo Design — Auswahlarbeit"
            }
          }
        ]
      },
      {
        "type": "image",
        "src": "/projects/logo-types/detail-10.webp",
        "li": 9,
        "alt": {
          "en": "Logo design — selected work",
          "de": "Logo Design — Auswahlarbeit"
        }
      },
      {
        "type": "imageGrid",
        "images": [
          {
            "src": "/projects/logo-types/detail-11.webp",
            "li": 10,
            "alt": {
              "en": "Logo design — selected work",
              "de": "Logo Design — Auswahlarbeit"
            }
          },
          {
            "src": "/projects/logo-types/detail-12.webp",
            "li": 11,
            "alt": {
              "en": "Logo design — selected work",
              "de": "Logo Design — Auswahlarbeit"
            }
          }
        ]
      },
      {
        "type": "image",
        "src": "/projects/logo-types/detail-13.webp",
        "li": 12,
        "alt": {
          "en": "Logo design — selected work",
          "de": "Logo Design — Auswahlarbeit"
        }
      },
      {
        "type": "imageGrid",
        "images": [
          {
            "src": "/projects/logo-types/detail-14.webp",
            "li": 13,
            "alt": {
              "en": "Logo design — selected work",
              "de": "Logo Design — Auswahlarbeit"
            }
          },
          {
            "src": "/projects/logo-types/detail-15.webp",
            "li": 14,
            "alt": {
              "en": "Logo design — selected work",
              "de": "Logo Design — Auswahlarbeit"
            }
          }
        ]
      }
    ],
    "imgs": [
      "/projects/logo-types/detail-01.webp",
      "/projects/logo-types/detail-02.webp",
      "/projects/logo-types/detail-03.webp",
      "/projects/logo-types/detail-04.webp",
      "/projects/logo-types/detail-05.webp",
      "/projects/logo-types/detail-06.webp",
      "/projects/logo-types/detail-07.webp",
      "/projects/logo-types/detail-08.webp",
      "/projects/logo-types/detail-09.webp",
      "/projects/logo-types/detail-10.webp",
      "/projects/logo-types/detail-11.webp",
      "/projects/logo-types/detail-12.webp",
      "/projects/logo-types/detail-13.webp",
      "/projects/logo-types/detail-14.webp",
      "/projects/logo-types/detail-15.webp"
    ]
  }
};

/* ===== Universal export: works in browser AND Node (SSR). Browser ignores this. ===== */
if (typeof module !== 'undefined' && module.exports) { module.exports = { P: P }; }
